api_platform:
  title: 'Lab 6 API'
  version: '1.0.0'
  # We will use /api as a prefix (see config/routes/api_platform.yaml)
  formats:
    jsonld:
      mime_types: ['application/ld+json']
    json:
      mime_types: ['application/json']
