# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\EventListener\RuntimeConstraintExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # Lab 8: API Platform Doctrine ORM Extensions (for collections + items)
    App\Extension\ProjectOwnerExtension:
        tags:
            - { name: 'api_platform.doctrine.orm.query_extension.collection' }
            - { name: 'api_platform.doctrine.orm.query_extension.item' }

    App\Extension\TaskCreatorExtension:
        tags:
            - { name: 'api_platform.doctrine.orm.query_extension.collection' }
            - { name: 'api_platform.doctrine.orm.query_extension.item' }
